name: vinylhub
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  html: ^0.15.5  # Cambié a la versión sugerida

  # Firebase packages
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.1.0
  firebase_messaging: ^15.1.6


  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  fluttertoast: ^8.2.1
  http: ^1.2.2
  font_awesome_flutter: ^10.8.0
  image: ^4.0.15
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0

  geocoding: ^2.1.0
  geolocator: ^10.0.0
  google_maps_flutter: ^2.5.0

  cupertino_icons: ^1.0.8
  firebase_remote_config: ^5.2.0
  share_plus: ^10.1.4
  flutter_launcher_icons: ^0.14.3
  google_sign_in: ^6.2.2
  provider: ^6.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
    - assets/google_logo.png
